### ISSUE TITLE
Spit does not export a promise

### ISSUE THREAD

**Issue by steffenmllr** [nlf/wadofgum#2]
Hey there, nice model library. I wanted to write a joi based model thing for ages :)
One thing `Spit` does not export a `Promise` object at the moment.

Also it seems as if all the event tests are failing on my local machine. with `node` / `io` latest.

**Comment by nlf** [comment]
Spit removed the re-exporting of Promise, I haven't gotten around to updating wadofgum to account for that yet.

**Comment by nlf** [comment]
Closed via d6efe38cc11d5a6bf1ad29a63b375e39579b3b51
