### ISSUE TITLE
Changes

### ISSUE THREAD

**Issue by simon-p-r** [nlf/wadofgum#6]
Hi

The changes have removed the ability to set the type added in #4 which was an attempt to fix issue #3.    Also I can't seem to set and get properties on the class rather than the instance of class.  Is this intentional?

Thanks
Simon

**Comment by fritzy** [comment]
Sorry @simon-p-r. I moved your cheese. I made wadofgum to be stateless in the sense that it doesn't store properties anymore. It's methods always take an object and spit a new one out (pure functions). This made the code simpler, removed the need for making an instance for every model, etc. So you can make instances for different models without extending.

I did this for fritzy/sqlmoses and we'll likely incorperate it into nlf/muckraker.

If you prefer the old way, you could fork the last major version of that. Sorry for screwing things up for you.

**Comment by simon-p-r** [comment]
No worries @fritzy, I have not really tried functional programming so not sure of the benefits.  The problem I have is setting props on the instance of class as opposed to a static on class, for example all models that are instance of a class must share a schema which is set on the class not on every instance created.  Anyway I have hacked around issue for now but think there must be a better way!  

Cheers
Simon
